name: Build and Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "The environment to deploy to"
        type: string

      path:
        required: true
        description: "The path to the Terraform configuration files"
        type: string

jobs:
  # plan:
  #   name: Plan Terraform
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: 1.8.1
  #         terraform_wrapper: false

  #     - name: Terraform Init
  #       run: terraform init --backend="env/backend_s3_${{inputs.environment}}.hcl"

  #     - name: Terraform Plan
  #       run: terraform plan -var-file="env/${{inputs.environment}}.tfvars"

  apply:
    name: Apply Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    environment:
      name: prod
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.1
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init --backend="env/backend_s3_${{inputs.environment}}.hcl"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="env/${{inputs.environment}}.tfvars"

    #     apply:
    # name: Apply Terraform
    # runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   pull-requests: write
