name: Build and Test Client

on:
  workflow_call:
    inputs:
      api_gateway_url:
        required: false
        type: string
        description: "The API Gateway URL"
      cognito_user_pool_id:
        required: false
        type: string
        description: "The Cognito User Pool ID"
      cognito_user_pool_client_id:
        required: false
        type: string
        description: "The Cognito User Pool Client ID"
      environment:
        required: false
        type: string
        description: "The environment to deploy to"
        default: "dev"

jobs:
  build-and-test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        if: inputs.environment == 'prod'
        run: |
          echo "VITE_API_URL=${{ inputs.api_gateway_url }}" >> .env &&
          echo "VITE_USER_POOL_ID=${{ inputs.cognito_user_pool_id }}" >> .env &&
          echo "VITE_USER_POOL_CLIENT_ID=${{ inputs.cognito_user_pool_client_id }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
        env:
          CI: true

      - name: Upload production-ready build files
        if: inputs.environment == 'prod'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./client/dist
