name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  inspect-changes:
    name: Inspect Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      is-client: ${{ steps.changes.outputs.is-client }}
      is-client-infra: ${{ steps.changes.outputs.is-client-infra }}
      is-server-infra: ${{ steps.changes.outputs.is-server-infra }}
      is-lambda: ${{ steps.changes.outputs.is-lambda }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inspect Changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            is-client: 
              - 'client/**'
            is-client-infra: 
              - 'infrastructure/client/*'
            is-server-infra: 
              - 'infrastructure/server/*'
            is-lambda:
              - 'lambdas/**'

  build-and-test-client:
    name: Build and Test Client
    needs: inspect-changes
    if: github.event_name == 'push' || needs.inspect-changes.outputs.is-client == 'true'
    uses: ./.github/workflows/build-and-test-client.yml

  validate-and-format-client-infra:
    name: Validate and Format Client Infrastructure
    needs: inspect-changes
    if: github.event_name == 'push' || needs.inspect-changes.outputs.is-client-infra == 'true'
    uses: ./.github/workflows/validate-terraform.yml
    with:
      directory: client

  validate-and-format-server-infra:
    name: Validate and Format Server Infrastructure
    needs: inspect-changes
    if: github.event_name == 'push' || needs.inspect-changes.outputs.is-server-infra == 'true'
    uses: ./.github/workflows/validate-terraform.yml
    with:
      directory: server

  validate-and-format-lambdas:
    name: Validate and Format Lambdas
    needs: inspect-changes
    if: github.event_name == 'push' || needs.inspect-changes.outputs.is-lambda == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Black
        uses: psf/black@stable
