name: Deploy Client to S3

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to"

jobs:
  deploy-client:
    name: Deploy Client to S3
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: eu-west-2
          audience: sts.amazonaws.com

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Push to S3
        run: aws s3 cp production-files s3://${{inputs.environment}}-crossword-scoreboard-frontend/ --recursive

    #     - name: Checkout
    #         uses: actions/checkout@v4

    #     - name: Setup Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #     node-version: 14

    # - name: Install Dependencies
    #     run: npm install

    # - name: Build
    #     run: npm run build

    # - name: Push to S3
    #     run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
