name: Deploy to Prod

on:
  workflow_dispatch:
  push:
    branches:
      - add-cd-pipeline

jobs:
  validate-and-format-client-infra:
    name: Validate and Format Client Infrastructure
    uses: ./.github/workflows/validate-terraform.yml
    with:
      path: ./infrastructure/client

  apply-client-infra:
    needs: validate-and-format-client-infra
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    name: Apply Client Infrastructure
    uses: ./.github/workflows/apply-terraform.yml
    with:
      path: ./infrastructure/client
      environment: prod

  validate-and-format-server-infra:
    name: Validate and Format Server Infrastructure
    uses: ./.github/workflows/validate-terraform.yml
    with:
      path: ./infrastructure/server

  apply-server-infra:
    needs: validate-and-format-server-infra
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    name: Apply Server Infrastructure
    uses: ./.github/workflows/apply-terraform.yml
    with:
      path: ./infrastructure/server
      environment: prod

  deploy-client:
    name: Deploy Client to S3
    needs: apply-client-infra
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-client.yml
    with:
      environment: prod
