name: Validate Terraform

on:
  workflow_call:
    inputs:
      path:
        required: true
        description: "The path to the Terraform configuration files"
        type: string

jobs:
  validate-and-format-infrastructure:
    name: Validate and Format Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.1

      - name: Terraform Init
        run: |
          terraform init --backend=false
          terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
